name: Audit
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  pull_request:
env:
  CARGO_INCREMENTAL: 0
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
jobs:
  audit:
    name: audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          {% if rs-channel == "stable" %}
          toolchain: {{ rs-version }}
          {% elif rs-channel == "nightly" %}
          toolchain: nightly-{{ rs-version }}
          {% endif %}
          default: true
          override: true
          profile: {{ rs-profile }}
      - name: Setup cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Generate Cargo.lock
        run: cargo generate-lockfile
      - name: Run security audit
        uses: rustsec/audit-check@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
