name: "Rust"
on:
  pull_request:
    paths:
      - src/**/*
      - Cargo.toml
      - Cargo.lock
  push:
    paths:
      - src/**/*
      - Cargo.toml
      - Cargo.lock
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: "{{rust-version}}"
          override: true
          components: rustfmt, clippy

      - name: Check formatting
        run: cargo fmt --check

      - name: Run Clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

      - name: Run cargo test
        run: cargo test --workspace --all-targets
