name: Build Template
on:
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * 5"
  push:
    branches: ["*"]
    paths-ignore:
      - "**/docs/**"
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: mytemplate
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cargo-generate/cargo-generate-action@latest
        with:
          name: ${{ env.PROJECT_NAME }}
          arguments: "--define project-description=mytemplate --define gh-username=dangreco --destination=${{ runner.temp }}"

      - name: Debug temp contents
        run: |
          echo "Runner temp: ${{ runner.temp }}"
          ls -R "${{ runner.temp }}"

    # steps:
    #   - uses: actions/checkout@v4
    #   - uses: cargo-generate/cargo-generate-action@latest
    #     with:
    #       name: ${{ env.PROJECT_NAME }}
    #   - uses: dtolnay/rust-toolchain@stable
    #     with:
    #       toolchain: stable
    #   # we need to move the generated project to a temp folder, away from the template project
    #   # otherwise `cargo` runs would fail
    #   # see https://github.com/rust-lang/cargo/issues/9922
    #   - run: |
    #       mv $PROJECT_NAME ${{ runner.temp }}/
    #       cd ${{ runner.temp }}/$PROJECT_NAME
    #       cargo check
